### ISSUE TITLE
[FEATURE] Typo3 11 LTS compatibility

### ISSUE THREAD

**Issue by andrekoller** [Kephson/paste_reference#1]

**Comment by p380** [comment]
> Hi, I will work on that and use the pull request from @mvoehringer

I checked and it doesn't work on TYPO3 11.

**Comment by Kephson** [comment]
Hi @p380 I know that, because of that there is no new version at the moment.
There are bigger changes to do than I thought about.

**Comment by Kephson** [comment]
Hi @jimit-net2typo not at the moment; we're working on that.
