### ISSUE TITLE
[BUG] Issue with the top.rawurlencode

### ISSUE THREAD

**Issue by taieb123** [Kephson/paste_reference#11]
## Summary / Description
Option from the context menu pastes reference after are not working.

## Version

Version 2.0.2

## Steps to reproduce
Paste content using the option paste reference after In the context menu.

## Expected behavior

Show an error on the console Navigator, and the functionality is not working.

## Actual behavior

Functionality not working.

### Additional

**Possible fix**

I found this as typo3 deprecation and now we can use the ``encodeURIComponent`` instead of ``top.rawurlencode()``

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-88428-ToprawurlencodeAndTopstr_replace.html

**Comment by Kephson** [comment]
Hi, thanks a lot for providing the pull request; it's included now and I released version 2.0.3.
