### ISSUE TITLE
[FEATURE] TYPO3 12 support

### ISSUE THREAD

**Issue by ifre** [Kephson/paste_reference#21]
Hi,
is a Typo3 12 support planned?
An Update would made my day. :D

Thanks a lot

**Comment by Kephson** [comment]
Hi, yes it's planned and I was asked to add a feature request for TYPO3 core.
At the moment I have to check until I can provide an update.

**Comment by spoonerWeb** [comment]
What's the status here? You won't get a new feature to v12 into the core now. :)

**Comment by Kephson** [comment]
Hey @spoonerWeb yes, you're right :rofl:, I think it' now more to do; pull request is welcome :wink:

**Comment by cyrakoenig** [comment]
What is the current situation here? Miss paste reference for my TYPO3 12 project ;)

**Comment by Kephson** [comment]
Hi @cyrakoenig you're welcome to send a pull request, atm I didn't find any time to update it for TYPO3 12. :open_mouth:

**Comment by spoonerWeb** [comment]
Are there any new plans? 😬

**Comment by Kephson** [comment]
Hi, there is a new branch for TYPO3 12.4 with preparations for v12, but the backend JavaScript is the hardest part and we need somebody to realize it with ES6.

**Comment by spoonerWeb** [comment]
@Kephson Do you have someon who can handle the JS issues? I would sponsor it. Customer needs it urgently and I can't handle the JS.

**Comment by Kephson** [comment]
currently it should work with the versions "dev-main", "dev-TYPO3_12" and "dev-development".
Just do a right click and select "paste reference after" to insert a reference after current elements.

**Comment by Kephson** [comment]
there are a lot of tests needed, at the moment also the EXT: doesn't work with mulitlanguage pages.

**Comment by Shotte** [comment]
@Kephson  Any progress here? 

I tried "dev-main" and "dev-TYPO3_12" branches by downloding as zip installing via backend into Typo3 v12.4.8. After following your advice by "doing a right click and select "paste reference after" to insert a reference after current elements" I get this error message: 
"1: The record "Reference" couldn't be saved due to disallowed value(s)."

Any ideas?

**Comment by Kephson** [comment]
Hi @Shotte I will try to follow your problems and test the integration.

**Comment by christophlehmann** [comment]
Nice Extension! Works so far in v12, but only via Context Menu. Would be a nice TYPO3 v13 core feature.

**Comment by christophlehmann** [comment]
I have installed EXT:container. 
In a two column container element i have a header element. When i use "Paste after as reference", then the new reference is created as an "unused element" and not in the container after the header element.
<img width="1075" alt="Bildschirmfoto 2024-01-29 um 14 21 24" src="https://github.com/Kephson/paste_reference/assets/4953689/1e14e42e-2a29-46e0-aed9-c6651fafe6d9">

**Comment by saitho** [comment]
Right now I get a JS error when loggin in as an editor, where `top.pasteReferenceAllowed` is empty, resulting in:
> Uncaught SyntaxError: Unexpected token ';'

The issue lies in https://github.com/Kephson/paste_reference/blob/TYPO3_12/Classes/Hooks/PageLayoutController.php#L99, where the boolean return value from the PHP function is not processed into a boolean value for JavaScript. Casting to `(int)` may be sufficient, haven't checked the JS implementation yet.

**Comment by Kephson** [comment]
You could try to use the version [dev-TYPO3_12](https://packagist.org/packages/ehaerer/paste-reference#dev-TYPO3_12) form packagist to test the problem with the JS error. Did not had the time to check this in detail.
I'm still working on a version with all old features in the [dev-development](https://packagist.org/packages/ehaerer/paste-reference#dev-development) version.

**Comment by ulrichmathes** [comment]
See #37  for reference preview (blue background and _Edit_ button).

**Comment by DavidBruchmann** [comment]
In https://github.com/DavidBruchmann/paste_reference/tree/david-v12.4 the additional button is now working, to paste content from another page.
I'll proceed working, to get the common modal with three options (cancel, paste as copy, paste as reference) working.

@ulrichmathes perhaps you can explain more detailed some GUI related aspects?

**Comment by DavidBruchmann** [comment]
The PR for TYPO3 v12 can be tested, and I'd be happy about any feedback:
https://github.com/Kephson/paste_reference/pull/50

**Comment by DavidBruchmann** [comment]
Please see #55 for a newer PR with compatibility for TYPO3 v12.

**Comment by DavidBruchmann** [comment]
solved with #56, please open a new issue for any new bugs or feature requests.
