### ISSUE TITLE
[BUG] Call to undefined method EHAERER\PasteReference\Helper\Helper::getInstance()

### ISSUE THREAD

**Issue by mhirdes** [Kephson/paste_reference#26]
## Summary / Description
After installation I got this error, when I click on the page module and then on a page in the page tree.

## Version

dev-TYPO3_12
PHP 8.2
TYPO3 12.4.7 

## Steps to reproduce

see Summary

## Expected behaviour

No error

## Actual behavior

see screen

![16-11-_2023_13-38-17](https://github.com/Kephson/paste_reference/assets/915162/24f2e632-1bab-4d58-b371-e2c30e308666)

**Comment by simonschaufi** [comment]
The ShortcutPreviewRenderer class is not yet migrated. How are you able to call this class? For me I can create references without using that class.

**Comment by simonschaufi** [comment]
ok that helps. With standard pages it works so far.

**Comment by Kephson** [comment]
could you please update, I pushed an update of version dev-main, dev-TYPO3_12 and dev-development.
jQuery is now removed and the message of the modal has changed to show it as "reference".
