### ISSUE TITLE
References not working with EXT:container

### ISSUE THREAD

**Issue by spoonerWeb** [Kephson/paste_reference#27]
I have installed EXT:container. 
In a two column container element i have a header element. When i use "Paste after as reference", then the new reference is created as an "unused element" and not in the container after the header element.
<img width="1075" alt="Bildschirmfoto 2024-01-29 um 14 21 24" src="https://github.com/Kephson/paste_reference/assets/4953689/1e14e42e-2a29-46e0-aed9-c6651fafe6d9">

**Payload paste reference after**
<img width="602" alt="Bildschirmfoto 2024-01-29 um 14 35 30" src="https://github.com/Kephson/paste_reference/assets/4953689/907573eb-b866-48a7-b361-52ca05b8b979">

**Payload copy after**
<img width="489" alt="Bildschirmfoto 2024-01-29 um 14 35 20" src="https://github.com/Kephson/paste_reference/assets/4953689/e818d610-ad40-457d-a0e1-f19d86237949">

_Originally posted by @christophlehmann in https://github.com/Kephson/paste_reference/issues/21#issuecomment-1914688146_

**Comment by spoonerWeb** [comment]
Problem is that the information of `tx_container_parent` is missing. Adding the correct UID into DB and the reference is right. 

Will create a PR.

**Comment by PKuhlmay** [comment]
This now works for me in the **TYPO3_12** branch.

**Comment by felixranesberger** [comment]
Make sure to add `shortcut` to your allowed `CType` container configuration, because otherwise you can't insert the reference. 

```
'allowed' => ['CType' => 'header,text,image,shortcut'],
```
