### ISSUE TITLE
[BUG] TYPO3_REQUEST not available in CLI context (TYPO3 12)

### ISSUE THREAD

**Issue by 3l73** [Kephson/paste_reference#30]
## Summary / Description

The global variable `TYPO3_REQUEST` is accessed without checking the existence.
After that the request ist used to retrieve the query parameters.

Within the CLI context this leads to the exception: 
Call to a member function getQueryParams() on null

See: Classes/DataHandler/ProcessCmdmap.php

## Version

development branch for TYPO3 12

## Steps to reproduce

-

## Expected behaviour

The command map should not be executed.

## Actual behavior

The CLI command will leads to an exception.

### Additional

**Possible fix**

Check if the server request is available or stop processing

```php
$request = $GLOBALS['TYPO3_REQUEST'] ?? null;
if (!($request instanceof ServerRequestInterface)) {
           return;
}
$queryParams = $request->getQueryParams();
```

**Comment by Kephson** [comment]
Hi, I merged your pull request and will close the ticket afters test is successfull.

**Comment by DavidBruchmann** [comment]
@Kephson can this issue be closed?

**Comment by Kephson** [comment]
Yes, we can close it, because it is resolved in the latest main branch and the v12 branch.
