### ISSUE TITLE
Broken crowdin integration

### ISSUE THREAD

**Issue by georgringer** [Kephson/paste_reference#38]
See the language directory which is currently filled with 1000s of files

I suggest to change the crowdin.yml to 
```
files:
  - source: /Resources/Private/Language/locallang*.xlf
    translation: /Resources/Private/Language/%two_letters_code%.%original_file_name%
```

+ remove all translations from the repository

until this is fixed, the extension won't get exported

**Comment by Kephson** [comment]
Hi Georg,
many thanks for reporting that; I removed all the files, but I have to change the settings in the Crowdin account because it creates pull requests.

**Comment by comradekingu** [comment]
Use Weblate instead?

**Comment by Kephson** [comment]
Should be fixed now, no files will be transferred to Git now.
