### ISSUE TITLE
[BUG] Translation of references

### ISSUE THREAD

**Issue by marclindemann** [Kephson/paste_reference#4]
## Summary / Description

Translation of Reference is not working. It will reference the initial language

## Version

2.0.0

## Steps to reproduce

past as reference a translated record

## Expected behaviour

show the translated record

## Actual behavior

it will show the origin language

**Comment by Kephson** [comment]
@marclindemann I will check this, could you please explain it in detail?
You're copying a translated element and it will not reference to the translated element?
