### ISSUE TITLE
[BUG] Exception in combination with calendarize record due to wrong type expected in DataHandler hook (in v12 / main)

### ISSUE THREAD

**Issue by sypets** [Kephson/paste_reference#45]
I realize version TYPO3 v12 is not released yet, I am using the latest  "main" branch. If my issue is not helpful, please feel free to close.

## Summary / Description

Edit tx_calendarize_domain_model_event record in BE - throws Exception

## Version

* TYPO3 12.4.18 (latest release)
* paste_reference: latest master / main

## Steps to reproduce

Unfortunately, I could not reproduce it on a minimal installation. We have several other extensions installed, including calendarize. But this is how I reproduced it on our site (which contain other extensions as well):

1. In BE, edit a calendarize event, e.g. in list module
2. Save

## Expected behaviour

No exception.

## Actual behavior

Exception is thrown and error message visible.

> `EHAERER\PasteReference\Hooks\DataHandler::processCmdmap(): Argument [#4 (closed)] $value must be of type string, array given,`
> `called in /var/www/site-uol12/vendor/typo3/cms-core/Classes/DataHandling/DataHandler.php on line 3528`

### Additional

**Reason for exception**

TYPO3 calls the hook with an array as 4. parameter ($value).

paste_reference expects string. 

**Source code:**

core DataHandler: 

`3528                             $hookObj->processCmdmap($command, $table, $id, $value, $commandIsProcessed, $this, $pasteUpdate);`

paste_reference: Hooks/DataHandler:

```
public function processCmdmap(
        string          $command,
        string          $table,
        int             $id,
        string          $value,

```

**Possible fix**

Maybe not use strict type for $value, DataHandler is very vague with the types, not clear to me if a string is expected and the problem is elsewhere. I also saw a bool when debugging. So there was at least array, string and bool.

Other extensions which also use this hook (e.g. wv_deepltranslate in AbstractTranslateHook or gridelements) also do not use strict type for parameter $value:

```
 public function processCmdmap(
        string $command,
        string $table,
        $id,
        $value,
```

**Comment by Kephson** [comment]
Hi @sypets did you use the "dev-TYPO3_12" branch for your TYPO3 12 installation?: https://packagist.org/packages/ehaerer/paste-reference#dev-TYPO3_12
Maybe this could be the problem.

**Comment by sypets** [comment]
@Kephson No, I used the latest "main" branch. I wil try the TYPO3_12 branch. Thanks.

**Comment by Kephson** [comment]
Ok, I merged the last TYPO3_12 branch into main to avoid problems with TYPO3 12 a little bit in the main branch.
