### ISSUE TITLE
ShortcutPreviewRenderer should also show time controlled references that are currently not visible

### ISSUE THREAD

**Issue by akiessling** [Kephson/paste_reference#5]
Hi,

The preview renderer for shortcuts filters out time controlled references that are currently not visible. This is a bit confusing for editors, since they might think that the element does not work. Thus i'd like to remove the restrictions for StartTime and EndTime. Do you agree? Then i will prepare a pull request

--> \EHAERER\PasteReference\PageLayoutView\ShortcutPreviewRenderer::collectContentData

```
$queryBuilder = $this->getQueryBuilder();
$queryBuilder->getRestrictions()->removeByType(\TYPO3\CMS\Core\Database\Query\Restriction\StartTimeRestriction::class);
$queryBuilder->getRestrictions()->removeByType(\TYPO3\CMS\Core\Database\Query\Restriction\EndTimeRestriction::class);
```

**Comment by Kephson** [comment]
Hi @akiessling I think you're right and will integrate and test it.
