### ISSUE TITLE
[FEATURE] TYPO3 13 support

### ISSUE THREAD

**Issue by DavidBruchmann** [Kephson/paste_reference#54]
Just as info, #53 provides TYPO3 v13 compatibility and testing functionality in the backend is welcome.
Any hints for improvements are naturally welcome too.

**Comment by Kephson** [comment]
There is now a TYPO3_13 branch where you can find the version for TYPO3 13: https://github.com/Kephson/paste_reference/tree/TYPO3_13
You can also find the version on packgist now to install it with Composer: https://packagist.org/packages/ehaerer/paste-reference#dev-TYPO3_13

**Comment by DavidBruchmann** [comment]
Great, actually I planned to spend still some time on it :D
Will check if it's even required ;-)

**Comment by Kleini13** [comment]
@DavidBruchmann I have installed the extension and tested it in TYPO3 13 (branch TYPO3_13). 

Here is some feedback:

- The context menu does not appear consistent with the past reference. As far as I have observed so far only when copying directly, the page is no longer reloaded, which is visible in the positioning of the buttons ‘t3js-paste-copy’ and ‘t3js-paste-new’. 
<img width="665" alt="Bildschirmfoto 2024-11-09 um 11 58 31" src="https://github.com/user-attachments/assets/65e3da04-4b72-4e1a-98e0-f5e3a1ce9deb">
<img width="639" alt="Bildschirmfoto 2024-11-09 um 11 58 54" src="https://github.com/user-attachments/assets/1f67a728-3a8f-4e30-b468-17738841c1a5">
- The "t3skin_override.css" is not compatible with dark mode. I made a attempt to fix this here: https://github.com/Kleini13/paste_reference/blob/main/Resources/Public/Backend/Css/Skin/t3skin_override.css 
<img width="625" alt="Bildschirmfoto 2024-11-09 um 12 10 46" src="https://github.com/user-attachments/assets/934ff681-2e0e-4061-8dca-58b7e4ec07ff">

- Changed the Button Edit in the "ShortcutPreviewRenderer.php". You can find the code here: https://github.com/Kleini13/paste_reference/blob/main/Classes/PageLayoutView/ShortcutPreviewRenderer.php
<img width="240" alt="Bildschirmfoto 2024-11-09 um 12 15 15" src="https://github.com/user-attachments/assets/9494491f-70e7-4253-9fc4-0072ac9eeb82">

Here how it looks ind dark mode:
<img width="623" alt="Bildschirmfoto 2024-11-09 um 12 16 23" src="https://github.com/user-attachments/assets/e4076533-c01c-46cd-874a-ce045ba8aaed">

**Comment by DavidBruchmann** [comment]
@Kleini13 thanks a lot for testing, the issues are similar to those I fixed in the v12 branch, and I expected them already.
About your code adjustments I'll have a look, thanks a lot for spending your efforts on it!

I hope I'm finding the time still this weekend, so that v13 can be released soon too.

**Comment by DavidBruchmann** [comment]
For those who "can't wait" :-) I've a new PR with adjustments in the JavaScript: #66

**Comment by DavidBruchmann** [comment]
Branch [TYPO3_13](https://github.com/Kephson/paste_reference/tree/TYPO3_13) ist updated with the PR

**Comment by Kephson** [comment]
I released the first version 4.0.0 for TYPO3 version 13 now.
The main branch is now the base branch for TYPO3 13 and above.
There are additional branches for other versions and tests: [TYPO3_13](https://github.com/Kephson/paste_reference/tree/TYPO3_13), [TYPO3_12](https://github.com/Kephson/paste_reference/tree/TYPO3_12), [TYPO3_11-5](https://github.com/Kephson/paste_reference/tree/TYPO3_11-5) and [TYPO3_10-4](https://github.com/Kephson/paste_reference/tree/TYPO3_10-4) if needed.
