### ISSUE TITLE
[Bug] Automated publishing in TER is failing (missing user access)

### ISSUE THREAD

**Issue by DavidBruchmann** [Kephson/paste_reference#57]
## Summary / Description

```
Publishing version 3.0.0 of extension paste_reference
=====================================================

Warning: ] Could not publish version 3.0.0 of extension paste_reference.        
           Reason: The user is not allowed to access this extension. 
```

I never need access, but someone has to publish it then ;-)

**Additionally**

I don't know how to create a release, this should be done too, for v3.0.0/v12 and and later for v4.0.0/v13

**Comment by sbuerk** [comment]
The tag should be removed from the repository and packagist anyway. Tagged to early.

**Comment by PKuhlmay** [comment]
Don't release the v12 version now. The v12 version is not yet finished.

**Comment by Kephson** [comment]
Hi together,
I removed the latest release 3.0.0 also from Packagist until there is a final version.
I will do the release, if we have a final working solution for TYPO3 v12 (v3.0.0) and TYPO3 13 (v4.0.0).
But at the moment please be focused on the v12 version until there is a final working release.
