### ISSUE TITLE
Version 3.0 disappeared from TER 

### ISSUE THREAD

**Issue by coding46** [Kephson/paste_reference#59]
I used the TYPO3 v12 compatible version (3.0.*) for testing from TER via composer. It is not available anymore. Is there a way to get it back? :)

**Comment by PKuhlmay** [comment]
Hi it was removed because it is not finished yet. The release was due to an accident. You could try the main branch but keep in mind that it is not officially released for version 12.

**Comment by DavidBruchmann** [comment]
the latest changes are pushed in branch TYPO3_12, so the branch main is not up to date.

**Comment by Kephson** [comment]
You can find here on Packagist: https://packagist.org/packages/ehaerer/paste-reference#dev-TYPO3_12

**Comment by simplychrislike** [comment]
Is there a list of things that still need an update? My first tests with TYPO3 12 where fine.

**Comment by DavidBruchmann** [comment]
thanks your positive feedback helps certainly.
Actually I'm waiting for some more feedback and that a release can be created if no more changes are requested.
I'm aware that the php code could be arranged a bit different, I did there some restructuring but changed my opinion about it later. I'm open to change it if requested. It doesn't effect functionality though.

**Comment by Kephson** [comment]
Hi, for me it's also fine at the moment; we have to make sure the code for TYPO3 13 is as clean as possible. But atm we can release a version 3 for TYPO3 12 if there are no problems.

**Comment by Kephson** [comment]
Version 3 is now available on Packagist and TER:
https://packagist.org/packages/ehaerer/paste-reference#3.0.0
https://extensions.typo3.org/extension/paste_reference
