### ISSUE TITLE
[FEATURE] Add more native look for content element backend preview

### ISSUE THREAD

**Issue by imminger** [Kephson/paste_reference#62]
## Summary / Description

When hovering over the backend preview of a content element, the header area gets a dark background. 

https://github.com/user-attachments/assets/39e9044c-c74b-4f33-8dd5-48e93295ce86

Tested with TYPO3 12 / paste_reference 3.0

## Describe the solution you'd like

When paste_reference is not installed, the header area of a content element backend preview stays white on hover. paste_reference should not change the look of the BE preview.

## Possible solution

Remove custom CSS: https://github.com/Kephson/paste_reference/blob/ec7180f99966a4533e7308b757a75548e7702ce3/Resources/Public/Backend/Css/Skin/t3skin_override.css#L37-L44

This might also prevent problems for a future TYPO3 13 release, which adds a dark / light theme

**Comment by Kephson** [comment]
Hi, we will check this problem an remove the CSS if it's not needed.
Could you provide a pull request?

**Comment by Kephson** [comment]
Hi,
I removed completely the backend CSS, because I think it's not needed anymore.
Please check the version "dev-main" or "dev-TYPO3_12" with the removed backend CSS and send feedback.

**Comment by imminger** [comment]
I tested it and it looks a lot better now. Thank you very much.

**Comment by Kephson** [comment]
Hi, there a new versions for TYPO3 v12 (3.0.1) and TYPO3 v13 (4.0.0) which includes these changes.
