### ISSUE TITLE
[BUG] Paste language translated content element as reference

### ISSUE THREAD

**Issue by zoranilic** [Kephson/paste_reference#63]
## Summary / Description

When translated content element is pasted as reference in default of other languages then a default sys_language_uid is used.

## Version

paste_reference v3.0.0
TYPO3 v12.4.22

## Steps to reproduce

Copy translated content element and paste as reference to any language on any page. It will be invisible there because wrong sys_language_uid is assigned to Reference - "Insert Records (shortcut)" content element.

## Expected behaviour

Reference content element should be visible where it is pasted.

## Actual behavior

It's invisible after paste.

### Additional

**Possible fix**

Class Method EHAERER\PasteReference\ContextMenu\PasteReferenceItemProvider::getAdditionalAttributes needs sys_language_uid assigned to "CB[update]" like this:

```
$urlParameters = [
            'prErr' => 1,
            'uPT' => 1,
            'CB[paste]' => $this->table . '|' . -$this->record['uid'],
            'CB[pad]' => 'normal',
            'CB[update]' => [
                'colPos' => $this->record['colPos'],

                // Correct language - bug fix
                'sys_language_uid' => $this->record['sys_language_uid'],
            ],
            'reference' => 1,
        ];
```

***Miscellaneous***

...

**Comment by zoranilic** [comment]
Hi, @Kephson Yes. It works. Also works when pasting reference from one language to another.
I'll provide pull request soon.

**Comment by Kephson** [comment]
Many thanks, I merged it to TYPO3_12 branch first and after testing it finally I will release a new version.
