### ISSUE TITLE
[REGRESSION] reference preview colored overlay missing?

### ISSUE THREAD

**Issue by ulrichmathes** [Kephson/paste_reference#71]
## Summary / Description
The styling of the reference preview is not styled anymore as all custom styles where removed in e6eb6d854eab00154a4855392eb1d6c702575c1c. 

## Version
3.0.1
4.0.0

## Expected behaviour
![image](https://github.com/user-attachments/assets/e5d3137e-6395-4cee-8916-d259b5d79236)

## Actual behavior
![image](https://github.com/user-attachments/assets/f46667e2-b50f-4eda-96fe-e1ba5d658022)

### Additional
Maybe this isn't in scope anymore. But there still is (in Version 3.0.2)  an div placed over the reference content `#reference-overlay`. Which has no meaning without the styles.

**Possible fix**
I could provide an PR with the minimal styles needed for this feature. But only if its still in scope of paste_reference.

**Comment by DavidBruchmann** [comment]
Thanks for the report.
v3.x should still be supported as it's for TYPO3 v12.
So we've to refine which CSS still is useful and add the removed CSS partially again.
As explanation, the removal solved issue #62.

**Comment by DavidBruchmann** [comment]
@ulrichmathes your offer to provide a fix is very appreciated, that would be great!

**Comment by ulrichmathes** [comment]
i managed to use only backend css classes.
Should i create seperate PR for TYPO3_12 and TYPO3_13 Branches?

**Comment by DavidBruchmann** [comment]
Thanks a lot!
I verified the added classes according to the desired presentation and it looks good.
@Kephson I think we can merge it like this in both branches, and separate PRs are likely not required @ulrichmathes .

**Comment by DavidBruchmann** [comment]
After the latest 2 releases I think this issue can be closed.
Thanks again for the report and work on it!
