### ISSUE TITLE
[BUG] Drag&droping container children from one column to the other returns error

### ISSUE THREAD

**Issue by SruthiKumar333** [Kephson/paste_reference#9]
## Summary / Description

Moving children of a multicolumn container from one column to another loses colPos and returns error.

Response to the ajax call is :
`{"redirect":"","messages":[{"title":"","message":"1: These fields of record 9554 in table \u0022tt_content\u0022 have not been saved correctly: colPos! The values might have changed due to type casting of the database.","severity":2}],"hasErrors":true}`

Possibly the same issue as #6 and b13/container#297
This is said to be fixed for versions>=2.0.1, but not for Typo3 10 compatible versions. 

## Version
_Tested versions_
EXT:paste_reference 1.0.2
EXT: container 2.1.1, 2.1.0
TYPO3: 10.4.31

## Steps to reproduce

Add a sample multicolumn container to a page and add child elements. Try moving child elements from one column to another by drag&droping.

**Comment by Kephson** [comment]
Hi, thanks for reporting; I have to check the issue and also the referenced issues to clarify whats exactly the problem.

**Comment by mikestreety** [comment]
Hello,

Have run into the same issue - implementing the same fix as mentioned in the various issues resolves it

https://github.com/Kephson/paste_reference/pull/10


As a chain of reading...

1. First issue reported on container repo: https://github.com/b13/container/issues/297
2. Which caused #6 to be made
3. This is the same issue but for v10 sites

Hope that all makes sense!

**Comment by Kephson** [comment]
Thanks a lot for your help and information. I provided a new version 1.0.3 for TYPO3 lower than 11.5.
I created a new branch TYPO3_10-4 to support the old version of the extension.
Closed with 2c8dfea5f14e574abf14173047a853d1f21155b8 and release of version 1.0.3.
Thanks a lot to @mikestreety and @SruthiKumar333 !
